let TransactionSubCategories = {
    'AUTO_INSURANCE ': 'Auto Insurance',
    'AUTO_PAYMENT ': 'Auto Payment',
    'GAS ': 'Gas',
    'PARKING ': 'Parking',
    'PUBLIC_TRANSPORTATION ': 'Public Transportation',
    'SERVICE_AND_PARTS ': 'Service & Parts',
    'DOMAIN_NAMES ': 'Domain Names',
    'FRAUD_PROTECTION ': 'Fraud Protection',
    'HOME_PHONE ': 'Home Phone',
    'HOUSING ': 'Hosting',
    'INTERNET ': 'Internet',
    'MOBILE_PHONE ': 'Mobile Phone',
    'TELEVISION ': 'Television',
    'UTILITIES ': 'Utilities',
    'ADVERTISING ': 'Advertising',
    'LEGAL ': 'Legal',
    'OFFICE_SUPPLIES ': 'Office Supplies',
    'PRINTING ': 'Printing',
    'SHIPPING ': 'Shipping',
    'BOOKS_AND_SUPPLIES ': 'Books & Supplies',
    'STUDENT_LOAN': 'Student Loan',
    'TUITION ': 'Tuition',
    'AMUSEMENT ': 'Amusement',
    'ARTS ': 'Arts',
    'MOVIES_AND_DVDS ': 'Movies & DVDs',
    'MUSIC ': 'Music',
    'NEWSPAPERS_AND_MAGAZINES ': 'Newspapers & Magazines',
    'ATM_FEE ': 'ATM Fee',
    'BANKING_FEE ': 'Banking Fee',
    'FINANCE_CHARGE ': 'Finance Charge',
    'LATE_FEE ': 'Late Fee',
    'SERVICE_FEE ': 'Service Fee',
    'TRADE_COMMISSIONS ': 'Trade Commissions',
    'FINANCIAL_ADVISOR ': 'Financial Advisor',
    'LIFE_INSURANCE ': 'Life Insurance',
    'ALCOHOL_AND_BARS ': 'Alcohol & Bars',
    'COFFEE_SHOPS ': 'Coffee Shops',
    'FAST_FOOD ': 'Fast Food',
    'GROCERIES ': 'Groceries',
    'RESTAURANTS ': 'Restaurants',
    'CHARITY ': 'Charity',
    'GIFT ': 'Gift',
    'DENSTIST ': 'Dentist',
    'DOCTOR ': 'Doctor',
    'EYECAR ': 'Eyecare',
    'GYM ': 'Gym',
    'HEALTH_INSURANCE ': 'Health Insurance',
    'PHARMACY ': 'Pharmacy',
    'SPORTS ': 'Sports',
    'FURNISHINGS ': 'Furnishings',
    'HOME_IMPROVEMENT ': 'Home Improvement',
    'HOME_INSURANCE ': 'Home Insurance',
    'HOME_SERVICES ': 'Home Services',
    'HOME_SUPPLIES ': 'Home Supplies',
    'LAWN_AND_GARDEN ': 'Lawn & Garden',
    'MORTGAGE_AND_RENT ': 'Mortgage & Rent',
    'BONUS ': 'Bonus',
    'INTEREST_INCOME ': 'Interest Income',
    'PAYCHECK ': 'Paycheck',
    'REIMBURSEMENT ': 'Reimbursement',
    'RENTAL_INCOME ': 'Rental Income',
    'BUY ': 'Buy',
    'DEPOSIT ': 'Deposit',
    'DIVIDEND_AND_CAP_GAINS ': 'Dividend & Cap Gains',
    'SELL ': 'Sell',
    'WITHDRAWAL ': 'Withdrawal',
    'ALLOWANCE ': 'Allowance',
    'BABY_SUPPLIES ': 'Baby Supplies',
    'BABYSITTER_AND_DAYCARE ': 'Babysitter & Daycare',
    'CHILD_SUPPORT ': 'Child Support',
    'KIDS_ACTIVITIES ': 'Kids Activities',
    'TOYS ': 'Toys',
    'HAIR ': 'Hair',
    'LAUNDRY ': 'Laundry',
    'SPA_AND_MASSAGE ': 'Spa & Massage',
    'PET_FOOT_AND_SUPPLIES ': 'Pet Food & Supplies',
    'PET_GROOMING ': 'Pet Grooming',
    'VETERINARY ': 'Veterinary',
    'BOOKS ': 'Books',
    'CLOTHING ': 'Clothing',
    'ELECTRONICS_AND_SOFTWARE ': 'Electronics & Software',
    'HOBBIES ': 'Hobbies',
    'SPORTING_GOODS ': 'Sporting Goods',
    'FEDERAL_TAX ': 'Federal Tax',
    'LOCAL_TAX ': 'Local Tax',
    'PROPERTY_TAX ': 'Property Tax',
    'SALES_TAX ': 'Sales Tax',
    'STATE_TAX ': 'State Tax',
    'CREDIT_CARD_PAYMENT ': 'Credit Card Payment',
    'TRANSFOR_FOR_CASHING_SPENDING ': 'Transfer for Cash Spending',
    'MORTGAGE_PAYMENT ': 'Mortgage Payment',
    'AIR_TRAVEL ': 'Air Travel',
    'HOTEL ': 'Hotel',
    'RENTAL_CAR_AND_TAXI ': 'Rental Car & Taxi',
    'VACATION ': 'Vacation',
    'CASH ': 'Cash',
    'CHECK ': 'Check',
}

export default Object.freeze(TransactionSubCategories)
