let TransactionCategories = {
    // 'ENTERTAINMENT': 'Entertainment',
    // 'FEES': 'Fees',
    // 'GROCERIES': 'Groceries',
    // 'HEALTH': 'Health',
    // 'HOUSING': 'Rent / Mortgage',
    // // 'INCOME': 'Income',
    // 'RESTAURANTS': 'Restaurants',
    // 'SHOPPING': 'Shopping',
    // 'TRANSPORTATION': 'Transporation',
    // 'TRANSFER': 'Transfer',
    // 'TRAVEL': 'Travel',
    // 'UTILITIES': 'Utilities',
    // 'OTHER': 'Other',
    'Auto & Transport': 'Auto & Transport',
    'Bills & Utilities' : 'Bills & Utilities',
    'Business Services': 'Business Services',
    'Education': 'Education',
    'Entertainment': 'Entertainment',
    'Fees & Charges': 'Fees & Charges',
    'Financial': 'Financial',
    'Food & Dining': 'Food & Dining',
    'Gifts & Donations': 'Gifts & Donations',
    'Health & Fitness': 'Health & Fitness',
    'Home': 'Home',
    // 'Income': 'Income',
    'Investments': 'Investments',
    'Kids': 'Kids',
    'Personal Care': 'Personal Care',
    'Pets': 'Pets',
    'Shopping': 'Shopping',
    'Taxes': 'Taxes',
    'Transfer': 'Transfer',
    'Travel': 'Travel',
    'Uncategorized': 'Uncategorized',
}

export default Object.freeze(TransactionCategories)
